Initialize project with components
Masouma96/React-BookStore pull request #1
Opened 2022-11-11 17:26 UTC by Masouma864

The Bookstore is a website that  allows you to:

Display a list of books.
Add a book.
Remove a selected book.

2022-11-11 18:07 UTC, codecaiine requested changes
Hi @Masouma864 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Good project implementation :heavy_check_mark: 
- No linters errors :heavy_check_mark: 
- Descriptive PR :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-11 18:07 UTC, codecaiine commented on src/components/book.js
> +/* eslint-disable */
- [ ] When I started the application  I noticed a linters error came up and also in your code you disable a lot **Eslint** . Please remove the **eslint disable** statement and try to fix all the errors you are getting. Because ` Eslint` helps developers to write clean JavaScript codes and adapt best practices when writing the code.  :+1:

2022-11-11 18:07 UTC, codecaiine commented on src/components/AddBook.js
> +/* eslint-disable */
- [ ] When I started the application  I noticed a linters error came up and also in your code you disable a lot **Eslint** . Please remove the **eslint disable** statement and try to fix all the errors you are getting. Because ` Eslint` helps developers to write clean JavaScript codes and adapt best practices when writing the code.  :+1:

2022-11-11 18:07 UTC, codecaiine commented on src/components/books.js
> +/* eslint-disable */
- [ ] When I started the application  I noticed a linters error came up and also in your code you disable a lot **Eslint** . Please remove the **eslint disable** statement and try to fix all the errors you are getting. Because ` Eslint` helps developers to write clean JavaScript codes and adapt best practices when writing the code.  :+1:

2022-11-11 18:07 UTC, codecaiine commented on src/components/categories.js
> +/* eslint-disable */
- [ ] When I started the application  I noticed a linters error came up and also in your code you disable a lot **Eslint** . Please remove the **eslint disable** statement and try to fix all the errors you are getting. Because ` Eslint` helps developers to write clean JavaScript codes and adapt best practices when writing the code.  :+1:

2022-11-12 06:32 UTC, Masouma864 commented on src/components/book.js
> +/* eslint-disable */
Thank you for your comments.
I remove them.

2022-11-12 06:34 UTC, Masouma864 commented on src/components/categories.js
> +/* eslint-disable */
Removed all eslint disable.

2022-11-12 06:45 UTC, OLIPLICHE approved these changes
Hi @Masouma864 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Highlights
- Implement the change requested from the previous review 👏 👏
-  Create React part of the App👏 👏
- Linter is green (the last commit have a green check mark (✅)) 👏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-12 07:09 UTC, merged